<?php

declare(strict_types=1);

/**
 * @file
 * Provides an entity import entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function entity_import_theme(): array {
  return [
    'entity_import' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for entity import templates.
 *
 * Default template: entity-import.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the entity import information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_entity_import(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function entity_import_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish entity imports.
      $storage = \Drupal::entityTypeManager()->getStorage('entity_import');
      $entity_import_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($entity_import_ids) as $entity_import) {
        $entity_import->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize entity imports.
      $storage = \Drupal::entityTypeManager()->getStorage('entity_import');
      $entity_import_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($entity_import_ids) as $entity_import) {
        $entity_import->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function entity_import_user_predelete(UserInterface $account): void {
  // Delete entity imports that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('entity_import');
  $entity_import_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($entity_import_ids)
  );
}
